server:
  port: 8000
spring:
  profiles:
    active: ${APP_PROFILE:dev}

  jpa:
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          emplo-client: # Nome da configuração do cliente
            provider: keycloak
            client-id: emplo-client
            client-secret: A7dNaBr9TZPX4ManpXQxmduIPgx31wpw
            authorization-grant-type: client_credentials
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/EmploControl
            jwk-set-uri: http://localhost:8080/realms/EmploControl/protocol/openid-connect/certs


#jwt.secret=${JWT_SECRET:MY-JWT-SECRET}
#jwt.duration=${JWT_DURATION:86400}

#spring.mvc.pathmatch.matching-strategy=ant-path-matcher
