spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/emplo_control_bd
    username: postgres
    password: 1235
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
      jdbc:
        lob:
          non_contextual_creation:true


